version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   container_name: ngrok-tunnel
  #   restart: unless-stopped
  #   environment:
  #     - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
  #   command: http 5000
  #   ports:
  #     - "4040:4040"

networks:
  default:
    name: app-network